import { env } from "cloudflare:workers";
export type SiteUser={id:string;email:string;displayName:string};
export const runtime=()=>env as unknown as {DB?:D1Database;SMTP_PASSWORD?:string};
export async function ensureAuthTables(db:D1Database){await db.batch([db.prepare("CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY,email TEXT UNIQUE NOT NULL,display_name TEXT NOT NULL,terms_version TEXT NOT NULL,terms_accepted_at TEXT NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP NOT NULL)"),db.prepare("CREATE TABLE IF NOT EXISTS email_challenges (id TEXT PRIMARY KEY,email TEXT NOT NULL,code_hash TEXT NOT NULL,expires_at TEXT NOT NULL,attempts INTEGER DEFAULT 0 NOT NULL,consumed_at TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP NOT NULL)"),db.prepare("CREATE TABLE IF NOT EXISTS user_sessions (token_hash TEXT PRIMARY KEY,user_id TEXT NOT NULL,expires_at TEXT NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP NOT NULL)")]);}
export async function sha256(v:string){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return [...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,"0")).join("");}
export function normalizeEmail(v:unknown){const e=String(v||"").trim().toLowerCase();return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(e)&&e.length<=254?e:null;}
export const cookie=(r:Request,n:string)=>(r.headers.get("Cookie")||"").match(new RegExp(`(?:^|;\\s*)${n}=([^;]+)`))?.[1]||null;
export const sameOrigin=(r:Request)=>r.headers.get("Origin")===new URL(r.url).origin;
export async function currentUser(r:Request):Promise<SiteUser|null>{const db=runtime().DB,t=cookie(r,"first_look_session");if(!db||!t)return null;await ensureAuthTables(db);const x=await db.prepare("SELECT u.id,u.email,u.display_name FROM user_sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>?").bind(await sha256(t),new Date().toISOString()).first<{id:string;email:string;display_name:string}>();return x?{id:x.id,email:x.email,displayName:x.display_name}:null;}
