"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowLeft } from "lucide-react";
import LifeLine from "./life-line";
import ProductControls from "./controls";

type Product = { id:number; slug:string; title:string; description:string; type:string; status:string; visibility:string; updated_at:string; latest_version:number|null; likes_total:number };
type History = { versions: { id:number; version_number:number; title:string; description:string; story:string; type:string; status:string; tags:string; product_url:string; change_note:string; created_at:string; media:{object_key:string;media_type:string}[] }[]; events:{id:number;event_type:string;version_number:number|null;likes_total:number|null;detail:string;created_at:string}[] };

export default function ProductsPage() {
  const [products,setProducts] = useState<Product[]>([]), [open,setOpen] = useState<number|null>(null), [history,setHistory] = useState<Record<number,History>>({}), [loading,setLoading] = useState(true), [error,setError] = useState("");
  useEffect(() => { fetch("/api/creations/mine").then((r) => r.ok ? r.json() as Promise<Product[]> : Promise.reject()).then(setProducts).catch(() => setError("请先登录后查看自己的产品")) .finally(() => setLoading(false)); }, []);
  async function toggle(product: Product) { if (open === product.id) { setOpen(null); return; } setOpen(product.id); if (!history[product.id]) { const response = await fetch(`/api/creations/history?creationId=${product.id}`); if (response.ok) { const data = await response.json() as History; setHistory((current) => ({ ...current, [product.id]: data })); } } }
  return <main className="min-h-dvh bg-[#f7f7f4] text-[#171717]"><header className="border-b border-black/10"><div className="mx-auto flex h-16 max-w-4xl items-center px-5"><Link href="/" className="inline-flex items-center gap-2 text-sm text-black/50"><ArrowLeft size={16} />返回发现</Link></div></header><section className="mx-auto max-w-4xl px-5 py-12"><p className="text-sm text-black/45">产品内容</p><h1 className="mt-2 text-4xl font-semibold tracking-[-.06em]">我的产品</h1><p className="mt-4 max-w-xl text-sm leading-6 text-black/55">每次正式发布都会留下一个版本。展开产品，就能看到它一路的变化。</p>{loading ? <p className="mt-10 text-sm text-black/45">正在读取产品...</p> : error ? <div className="mt-10 rounded-xl border border-black/10 bg-white p-7"><p className="text-sm text-black/55">{error}</p><Link href="/login?next=/account/products" className="mt-5 inline-block rounded-full bg-black px-5 py-3 text-sm text-white">去登录</Link></div> : products.length ? <div className="mt-10 divide-y divide-black/10 border-y border-black/10">{products.map((product) => <article key={product.id} className="py-5"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><button onClick={() => toggle(product)} aria-expanded={open === product.id} className="min-w-0 text-left"><span className="flex flex-wrap items-center gap-2"><span className="text-xl font-semibold tracking-[-.04em]">{product.title}</span><span className="rounded bg-black/[.06] px-2 py-1 text-[10px] text-black/55">{product.visibility === "published" ? "上架中" : product.visibility === "unpublished" ? "已下架" : "草稿"}</span><span className="text-xs text-black/40">{product.latest_version ? `版本 ${product.latest_version}` : "尚无版本"} · 喜欢 {product.likes_total}</span></span><span className="mt-2 block text-sm text-black/50">{product.description}</span></button><ProductControls id={product.id} slug={product.slug} title={product.title} visibility={product.visibility} onVisibilityChange={(visibility) => {setProducts((all) => all.map((item) => item.id === product.id ? {...item,visibility} : item)); fetch(`/api/creations/history?creationId=${product.id}`).then((r)=>r.ok?r.json() as Promise<History>:null).then((data)=>{if(data)setHistory((all)=>({...all,[product.id]:data}));});}}/></div>{open === product.id && <div className="mt-5 border-t border-black/10 bg-[#fafaf8] px-5 py-5">{history[product.id] ? <LifeLine versions={history[product.id].versions} events={history[product.id].events}/> : <p className="text-sm text-black/45">正在读取发展记录…</p>}</div>}</article>)}</div> : <div className="mt-10 rounded-xl border border-dashed border-black/15 bg-white p-10 text-center"><p className="text-sm text-black/50">你还没有发布产品。</p><Link href="/create" className="mt-4 inline-block border-b border-black text-sm">发布第一个产品</Link></div>}</section></main>;
}
