"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, Box, Check, CircleAlert, LayoutDashboard, Search, Shield, Users } from "lucide-react";

type Tab = "overview" | "products" | "users" | "reports";
type AdminData = {
  me: { id:string; email:string; displayName:string; role:"owner"|"admin" };
  counts: { users_total:number; products_total:number; published_total:number; reports_pending:number };
  products: Array<{ id:number; title:string; type:string; creator_name:string; visibility:string; created_at:string; admin_hidden:number }>;
  users: Array<{ id:string; email:string; display_name:string; created_at:string; disabled_at:string|null; admin_role:"owner"|"admin"|null }>;
  reports: Array<{ id:number; target_type:string; target_id:string; reason:string; status:string; created_at:string; reporter_name:string|null }>;
  actions: Array<{ id:number; action:string; target_type:string; target_id:string; detail:string; created_at:string; admin_name:string|null }>;
};

const labels: Record<string,string> = { published:"已公开",private:"仅自己可见",unpublished:"已下架",draft:"草稿",private_pending:"等待上传",admin_hidden:"后台隐藏",hide_creation:"隐藏产品",restore_creation:"恢复产品",disable_user:"禁用用户",enable_user:"恢复用户",grant_admin:"设为管理员",revoke_admin:"移除管理员",resolve_report:"处理举报" };
const tabs: Array<{id:Tab;label:string;icon:typeof LayoutDashboard}> = [{id:"overview",label:"概览",icon:LayoutDashboard},{id:"products",label:"产品管理",icon:Box},{id:"users",label:"用户管理",icon:Users},{id:"reports",label:"举报处理",icon:CircleAlert}];
const formatDate=(value:string)=>value?new Date(value.replace(" ","T")+(value.includes("Z")?"":"Z")).toLocaleDateString("zh-CN"):"-";

export default function AdminPage(){
  const[data,setData]=useState<AdminData|null>(null),[tab,setTab]=useState<Tab>("overview"),[query,setQuery]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState("");
  async function load(){setError("");const response=await fetch("/api/admin",{cache:"no-store"});if(response.status===403){setError("当前账号没有管理权限");return}if(!response.ok){setError("后台暂时无法打开，请稍后重试");return}setData(await response.json()as AdminData)}
  useEffect(()=>{load().catch(()=>setError("后台暂时无法打开，请稍后重试"))},[]);
  async function act(action:string,targetId:string|number){if(!confirm(action==="disable_user"?"确认禁用这个用户吗？":"确认执行这个操作吗？"))return;setBusy(`${action}:${targetId}`);setError("");try{const response=await fetch("/api/admin",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,targetId})}),result=await response.json()as{error?:string};if(!response.ok)throw Error(result.error||"操作失败");await load()}catch(problem){setError(problem instanceof Error?problem.message:"操作失败")}finally{setBusy("")}}
  const products=useMemo(()=>data?.products.filter(item=>`${item.title} ${item.creator_name} ${item.type}`.toLowerCase().includes(query.toLowerCase()))||[],[data,query]);
  const users=useMemo(()=>data?.users.filter(item=>`${item.display_name} ${item.email}`.toLowerCase().includes(query.toLowerCase()))||[],[data,query]);
  if(!data)return <main className="admin-loading"><div className="admin-loading-bar"/><p>{error||"正在打开管理后台..."}</p>{error&&<div><Link href="/login?next=/admin">重新登录</Link><Link href="/">返回首页</Link></div>}</main>;
  return <main className="admin-shell"><aside className="admin-sidebar"><div><Link href="/" className="admin-brand"><img src="/koi-logo.png" alt=""/><span>FIRST LOOK</span></Link><p className="admin-caption">管理后台</p></div><nav aria-label="后台导航">{tabs.map(item=>{const Icon=item.icon;return <button key={item.id} onClick={()=>{setTab(item.id);setQuery("")}} className={tab===item.id?"active":""}><Icon size={17}/>{item.label}{item.id==="reports"&&data.counts.reports_pending>0&&<b>{data.counts.reports_pending}</b>}</button>})}</nav><div className="admin-profile"><span>{data.me.displayName}</span><small>{data.me.role==="owner"?"所有者":"管理员"}</small></div></aside><section className="admin-main"><header className="admin-header"><div><p>FIRST LOOK ADMIN</p><h1>{tabs.find(item=>item.id===tab)?.label}</h1></div><div className="admin-header-actions">{(tab==="products"||tab==="users")&&<label className="admin-search"><Search size={16}/><span className="sr-only">搜索</span><input value={query} onChange={event=>setQuery(event.target.value)} placeholder={tab==="products"?"搜索产品或创作者":"搜索用户或邮箱"}/></label>}<button type="button" className="admin-back" onClick={()=>window.location.assign(`${window.location.origin}/`)}><ArrowLeft size={15}/>返回网站</button></div></header>{error&&<div role="alert" className="admin-error">{error}<button onClick={()=>setError("")}>关闭</button></div>}
  {tab==="overview"&&<><div className="admin-metrics"><article><span>用户</span><strong>{data.counts.users_total}</strong></article><article><span>全部产品</span><strong>{data.counts.products_total}</strong></article><article><span>公开产品</span><strong>{data.counts.published_total}</strong></article><article><span>待处理举报</span><strong>{data.counts.reports_pending}</strong></article></div><section className="admin-panel"><h2>最近管理记录</h2>{data.actions.length?<div className="admin-action-list">{data.actions.map(item=><div key={item.id}><span>{item.admin_name||"管理员"}</span><b>{labels[item.action]||item.action}</b><p>{item.detail||`${item.target_type} ${item.target_id}`}</p><time>{formatDate(item.created_at)}</time></div>)}</div>:<div className="admin-empty">还没有管理操作记录。</div>}</section></>}
  {tab==="products"&&<section className="admin-panel"><div className="admin-panel-title"><h2>产品列表</h2><span>{products.length} 个</span></div>{products.length?<div className="admin-table-wrap"><table><thead><tr><th>产品</th><th>创作者</th><th>状态</th><th>发布时间</th><th>操作</th></tr></thead><tbody>{products.map(item=><tr key={item.id}><td><b>{item.title}</b><small>{item.type}</small></td><td>{item.creator_name}</td><td><span className={`admin-status ${item.admin_hidden?"warning":""}`}>{labels[item.visibility]||item.visibility}</span></td><td>{formatDate(item.created_at)}</td><td>{item.admin_hidden?<button disabled={busy===`restore_creation:${item.id}`} onClick={()=>act("restore_creation",item.id)}>恢复</button>:!["draft","private_pending","finalizing","deleting"].includes(item.visibility)&&<button disabled={busy===`hide_creation:${item.id}`} onClick={()=>act("hide_creation",item.id)} className="danger">隐藏</button>}</td></tr>)}</tbody></table></div>:<div className="admin-empty">没有找到相关产品。</div>}</section>}
  {tab==="users"&&<section className="admin-panel"><div className="admin-panel-title"><h2>用户列表</h2><span>{users.length} 人</span></div>{users.length?<div className="admin-table-wrap"><table><thead><tr><th>用户</th><th>注册时间</th><th>身份</th><th>账号状态</th><th>操作</th></tr></thead><tbody>{users.map(item=><tr key={item.id}><td><b>{item.display_name}</b><small>{item.email}</small></td><td>{formatDate(item.created_at)}</td><td>{item.admin_role==="owner"?"所有者":item.admin_role==="admin"?"管理员":"用户"}</td><td><span className={`admin-status ${item.disabled_at?"warning":""}`}>{item.disabled_at?"已禁用":"正常"}</span></td><td><div className="admin-row-actions">{item.id!==data.me.id&&(item.disabled_at?<button onClick={()=>act("enable_user",item.id)}>恢复</button>:<button className="danger" onClick={()=>act("disable_user",item.id)}>禁用</button>)}{data.me.role==="owner"&&item.id!==data.me.id&&!item.disabled_at&&(item.admin_role==="admin"?<button onClick={()=>act("revoke_admin",item.id)}>移除管理员</button>:!item.admin_role&&<button onClick={()=>act("grant_admin",item.id)}>设为管理员</button>)}</div></td></tr>)}</tbody></table></div>:<div className="admin-empty">没有找到相关用户。</div>}</section>}
  {tab==="reports"&&<section className="admin-panel"><div className="admin-panel-title"><h2>举报记录</h2><span>{data.reports.length} 条</span></div>{data.reports.length?<div className="admin-report-list">{data.reports.map(item=><article key={item.id}><div><span>{item.status==="pending"?"待处理":"已处理"}</span><h3>{item.reason}</h3><p>对象：{item.target_type} {item.target_id}　举报人：{item.reporter_name||"匿名"}</p></div><time>{formatDate(item.created_at)}</time>{item.status==="pending"&&<button onClick={()=>act("resolve_report",item.id)}><Check size={15}/>标记已处理</button>}</article>)}</div>:<div className="admin-empty"><Shield size={30}/><p>目前没有举报记录。</p><small>用户举报入口会在互动模块中接入。</small></div>}</section>}
  </section></main>}
