"use client";
import { Check, Copy, Heart, Star } from "lucide-react";
import { useEffect, useState } from "react";
import ReportButton from "./report-button";
type State = { likes: number; favorites: number; shares: number; views: number; liked: boolean; favorited: boolean };
export default function ProductActions({ creationId, slug }: { creationId: number; slug: string }) {
  const [state, setState] = useState<State>({ likes: 0, favorites: 0, shares: 0, views: 0, liked: false, favorited: false }), [copied, setCopied] = useState(false), [error, setError] = useState("");
  useEffect(() => { fetch(`/api/creations/actions?creationId=${creationId}`).then((r) => r.ok ? r.json() as Promise<State> : Promise.reject()).then(setState).catch(() => undefined); fetch("/api/creations/actions", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ creationId, action: "view" }) }).then((r) => r.ok ? r.json() as Promise<{ views: number }> : Promise.reject()).then((data) => setState((current) => ({ ...current, views: data.views }))).catch(() => undefined); }, [creationId]);
  async function like() { setError(""); const response = await fetch("/api/creations/react", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ creationId }) }); if (response.status === 401) { location.assign(`/login?next=${encodeURIComponent(`/work/${slug}`)}`); return; } const data = await response.json() as { liked?: boolean; count?: number; error?: string }; if (!response.ok) { setError(data.error || "喜欢失败"); return; } setState((current) => ({ ...current, liked: Boolean(data.liked), likes: Number(data.count || 0) })); }
  async function favorite() { setError(""); const response = await fetch("/api/creations/actions", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ creationId, action: "favorite" }) }); if (response.status === 401) { location.assign(`/login?next=${encodeURIComponent(`/work/${slug}`)}`); return; } const data = await response.json() as { favorited?: boolean; favorites?: number; error?: string }; if (!response.ok) { setError(data.error || "收藏失败"); return; } setState((current) => ({ ...current, favorited: Boolean(data.favorited), favorites: Number(data.favorites || 0) })); }
  async function share() { setError(""); try { await navigator.clipboard.writeText(location.href); } catch { setError("链接复制失败，请手动复制当前网址"); return; } await fetch("/api/creations/actions", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ creationId, action: "share" }) }); setCopied(true); setState((current) => ({ ...current, shares: current.shares + 1 })); setTimeout(() => setCopied(false), 1800); }
  return <div className="mt-8"><div className="flex flex-wrap items-center gap-3"><button onClick={like} className={`inline-flex items-center gap-2 rounded-full px-5 py-3 text-sm font-medium ${state.liked ? "bg-[#e15d36] text-white" : "bg-black text-white"}`}><Heart size={16} fill={state.liked ? "currentColor" : "none"} />{state.liked ? "已喜欢" : "喜欢"}<span className="text-xs opacity-65">{state.likes}</span></button><button onClick={favorite} className={`inline-flex items-center gap-2 rounded-full px-5 py-3 text-sm font-medium ${state.favorited ? "bg-[#e15d36] text-white" : "border border-black/15 bg-white text-black"}`}><Star size={16} fill={state.favorited ? "currentColor" : "none"} />{state.favorited ? "已收藏" : "收藏"}<span className="text-xs opacity-65">{state.favorites}</span></button><button onClick={share} className="inline-flex items-center gap-2 rounded-full border border-black/15 bg-white px-5 py-3 text-sm font-medium">{copied ? <Check size={16} /> : <Copy size={16} />}{copied ? "链接已复制" : "分享"}</button><ReportButton creationId={creationId} /></div><div className="mt-4 flex items-center gap-4 text-xs text-black/45"><span>{state.views} 次浏览</span><span>{state.shares} 次分享</span></div>{error && <p className="mt-3 text-sm text-red-600">{error}</p>}</div>;
}
