"use client";
import { useState } from "react";
import { Flag, X } from "lucide-react";
const reasons = ["垃圾广告", "色情或暴力内容", "抄袭或侵权", "欺诈或虚假信息", "其他问题"];
export default function ReportButton({ creationId }: { creationId?: number }) {
  const [open,setOpen]=useState(false),[reason,setReason]=useState(reasons[0]),[detail,setDetail]=useState(""),[message,setMessage]=useState("");
  async function submit(){if(!creationId)return;setMessage("提交中…");const response=await fetch("/api/reports",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({targetType:"creation",targetId:creationId,reason,detail})});const result=await response.json() as{error?:string;message?:string};if(response.status===401){location.assign(`/login?next=${encodeURIComponent(location.pathname)}`);return}setMessage(response.ok?result.message||"举报已提交":result.error||"举报失败，请稍后重试");if(response.ok)setOpen(false)}
  return <><button onClick={()=>setOpen(true)} className="mt-4 inline-flex items-center gap-2 rounded-full border border-black/15 px-4 py-2 text-sm text-black/55"><Flag size={15}/>举报</button>{open&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/35 p-5"><section role="dialog" aria-modal="true" className="w-full max-w-md rounded-2xl bg-[#f7f7f4] p-6 shadow-2xl"><div className="flex items-center justify-between"><h2 className="text-xl font-semibold">举报这个产品</h2><button onClick={()=>setOpen(false)} aria-label="关闭"><X/></button></div><p className="mt-2 text-sm text-black/55">提交后产品会暂时下架，等待审核。</p><label className="mt-6 block text-sm font-medium">举报原因<select value={reason} onChange={e=>setReason(e.target.value)} className="mt-2 w-full rounded-lg border border-black/15 bg-white px-3 py-3">{reasons.map(item=><option key={item}>{item}</option>)}</select></label><label className="mt-4 block text-sm font-medium">补充说明（选填）<textarea value={detail} onChange={e=>setDetail(e.target.value)} maxLength={500} rows={4} className="mt-2 w-full rounded-lg border border-black/15 bg-white px-3 py-3"/></label>{message&&<p className="mt-3 text-sm text-black/60">{message}</p>}<div className="mt-6 flex justify-end gap-3"><button onClick={()=>setOpen(false)} className="rounded-full border border-black/15 px-4 py-2 text-sm">取消</button><button onClick={submit} className="rounded-full bg-black px-4 py-2 text-sm text-white">提交举报</button></div></section></div>}</>;
}
