const featured = [
  { name: "Papercut", description: "把复杂的研究资料，整理成一页清晰的决策简报。", maker: "Lena Chen", tag: "AI效率", metric: "2.4k 体验" },
  { name: "Mori", description: "为每一次散步生成一份属于你的城市观察。", maker: "一个独立开发者", tag: "AI生活", metric: "1.8k 收藏" },
  { name: "Relay", description: "把会议里的想法，变成下一步可以执行的任务。", maker: "Northstar Studio", tag: "AI办公", metric: "936 分享" },
];

export default function Home() {
  return <main className="min-h-screen bg-[#fafafa] text-[#111]">
      <header className="mx-auto flex h-20 max-w-7xl items-center justify-between border-b border-black/10 px-6 lg:px-10"><a href="#top" className="flex items-baseline gap-3"><span className="text-lg font-semibold tracking-[-0.04em]">FIRST LOOK</span><span className="hidden text-xs text-black/40 sm:inline">AI 创造发现平台</span></a><nav className="hidden items-center gap-8 text-sm text-black/60 md:flex"><a href="#works">浏览作品</a><a href="#share">分享作品</a><a href="#about">关于</a></nav><button className="rounded-full bg-black px-5 py-2.5 text-sm font-medium text-white">登录</button></header>
    <section id="top" className="mx-auto max-w-7xl px-6 pb-28 pt-28 lg:px-10 lg:pb-36 lg:pt-40"><p className="mb-8 text-xs font-medium uppercase tracking-[0.24em] text-black/45">A directory for the AI era</p><h1 className="max-w-4xl text-5xl font-medium leading-[1.02] tracking-[-0.065em] sm:text-6xl lg:text-[6.5rem]">让每一个 AI 创造，<br /><span className="text-black/35">都值得被看见。</span></h1><div className="mt-12 flex flex-col justify-between gap-8 border-t border-black/15 pt-6 sm:flex-row sm:items-end"><p className="max-w-sm text-lg leading-7 text-black/60">发现正在被创造的 AI 产品。<br />从一个想法，到第一次被使用。</p><div className="flex gap-3"><a href="#works" className="rounded-full bg-black px-6 py-3 text-sm font-medium text-white">浏览作品 ↗</a><a href="#share" className="rounded-full border border-black/20 px-6 py-3 text-sm font-medium">分享我的作品</a></div></div></section>
    <section id="works" className="border-t border-black/10 bg-white px-6 py-20 lg:px-10 lg:py-28"><div className="mx-auto max-w-7xl"><div className="mb-12 flex items-end justify-between"><div><p className="mb-3 text-xs uppercase tracking-[0.22em] text-black/40">Selected work</p><h2 className="text-3xl tracking-[-0.05em]">精选作品</h2></div><a href="#works" className="text-sm text-black/55">查看全部 ↗</a></div><div className="grid gap-4 lg:grid-cols-3">{featured.map((item, index) => <article key={item.name} className="group border border-black/12 bg-[#fafafa] p-5 transition hover:-translate-y-1 hover:border-black/35"><div className={`mb-8 flex aspect-[1.25] items-end justify-between p-5 ${index === 1 ? "bg-[#e8e8e8]" : "bg-[#dedede]"}`}><span className="text-3xl font-medium tracking-[-0.08em]">{item.name}</span><span className="text-xs uppercase tracking-[0.15em] text-black/45">0{index + 1}</span></div><div className="flex items-start justify-between gap-4"><h3 className="text-xl tracking-[-0.04em]">{item.name}</h3><span className="border border-black/15 px-2 py-1 text-[11px] text-black/55">{item.tag}</span></div><p className="mt-3 min-h-14 text-sm leading-6 text-black/58">{item.description}</p><div className="mt-6 flex justify-between border-t border-black/10 pt-4 text-xs text-black/45"><span>{item.maker}</span><span>{item.metric}</span></div></article>)}</div></div></section>
    <section id="about" className="mx-auto grid max-w-7xl gap-12 px-6 py-24 lg:grid-cols-[1fr_2fr] lg:px-10 lg:py-36"><p className="text-xs uppercase tracking-[0.22em] text-black/40">Why First Look</p><p className="max-w-3xl text-4xl leading-[1.08] tracking-[-0.06em] sm:text-5xl">这里没有成熟产品的宏大叙事。只有正在发生的创造，和愿意先看一眼的人。</p></section>
    <section id="share" className="border-t border-black/10 bg-black px-6 py-20 text-white lg:px-10 lg:py-28"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-10 sm:flex-row sm:items-end"><div><p className="mb-5 text-xs uppercase tracking-[0.22em] text-white/45">For creators</p><h2 className="max-w-xl text-5xl tracking-[-0.07em] sm:text-6xl">做了一个东西？<br />让它被看见。</h2></div><button className="w-fit rounded-full bg-white px-6 py-3 text-sm font-medium text-black">分享我的作品 ↗</button></div></section>
    <footer className="mx-auto flex max-w-7xl justify-between px-6 py-8 text-xs text-black/40 lg:px-10"><span>© 2026 First Look</span><span>Made for early creations.</span></footer>
  </main>;
}
