"use client";
import Link from "next/link";
import { FormEvent, useState } from "react";

export default function LoginPage(){
  const[email,setEmail]=useState(""),[code,setCode]=useState(""),[sent,setSent]=useState(false),[terms,setTerms]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
  const next=typeof window!=="undefined"&&new URLSearchParams(window.location.search).get("next")==="/create"?"/create":"/";
  async function send(){setBusy(true);setMessage("");try{const r=await fetch("/api/auth/email/send",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email})});const d=await r.json()as{error?:string};if(!r.ok)throw Error(d.error||"发送失败");setSent(true);setMessage("验证码已发送，请查看邮箱");}catch(e){setMessage(e instanceof Error?e.message:"发送失败");}finally{setBusy(false)}}
  async function verify(e:FormEvent){e.preventDefault();setBusy(true);setMessage("");try{const r=await fetch("/api/auth/email/verify",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,code,acceptTerms:terms})});const d=await r.json()as{error?:string};if(!r.ok)throw Error(d.error||"验证失败");window.location.assign(next);}catch(e){setMessage(e instanceof Error?e.message:"验证失败");}finally{setBusy(false)}}
  return <main className="min-h-dvh bg-[#f7f7f4] px-5 py-16 text-[#171717]"><section className="mx-auto max-w-md rounded-2xl border border-black/10 bg-white p-7 shadow-sm"><Link href="/" className="text-sm text-black/45">← 返回首页</Link><h1 className="mt-8 text-3xl font-semibold tracking-[-0.05em]">注册或登录</h1><p className="mt-2 text-sm leading-6 text-black/50">使用邮箱验证码。首次验证成功后创建 First Look 账号。</p><form onSubmit={verify} className="mt-8 space-y-5"><label className="block"><span className="mb-2 block text-sm font-medium">邮箱</span><div className="flex gap-2"><input type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="name@example.com" className="min-w-0 flex-1 rounded-lg border border-black/15 px-4 py-3 outline-none focus:border-black"/><button type="button" disabled={busy||!email} onClick={send} className="shrink-0 rounded-lg border border-black/15 px-4 text-sm disabled:opacity-40">{sent?"重新发送":"获取验证码"}</button></div></label>{sent&&<><label className="block"><span className="mb-2 block text-sm font-medium">验证码</span><input inputMode="numeric" maxLength={6} required value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,""))} placeholder="六位验证码" className="w-full rounded-lg border border-black/15 px-4 py-3 tracking-[0.35em] outline-none focus:border-black"/></label><label className="flex items-start gap-2 text-sm leading-5 text-black/55"><input type="checkbox" checked={terms} onChange={e=>setTerms(e.target.checked)} className="mt-1"/><span>首次注册时，我同意 First Look 用户协议和隐私政策</span></label><button disabled={busy||code.length!==6} className="w-full rounded-full bg-black px-5 py-3.5 text-sm font-medium text-white disabled:opacity-40">注册／登录</button></>}{message&&<p role="status" className={`text-sm ${message.includes("已发送")?"text-emerald-700":"text-red-600"}`}>{message}</p>}</form></section></main>;
}
